version: "3.9"

networks:
  fintech:
    driver: bridge

volumes:
  oracle-data:
  kafka-data:

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: fintech-oracle
    environment:
      ORACLE_PASSWORD: LocalPass123
      APP_USER: auth_service
      APP_USER_PASSWORD: auth_service
      ORACLE_DATABASE: FREEPDB1
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - fintech

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: fintech-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - fintech

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: fintech-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - fintech

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.3
    container_name: fintech-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - fintech

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: fintech-keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeit
    command: start-dev --http-port=8080 --hostname-strict=false
    networks:
      - fintech

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: fintech-mailhog
    ports:
      - "8025:8025"
    networks:
      - fintech
